### ISSUE TITLE
rgbw is working?

### ISSUE THREAD

**Issue by toshibochan** [PA7T/magic_home_strip_rgbw#1]
Hi @PA7T rgbw is working?

**Comment by toshibochan** [comment]
for install is just replace maximkulkin file with yours?

**Comment by toshibochan** [comment]
i try you code in my rgbw and is working good. just have one error in the make file.
change this:
$(abspath ../../components/common/cJSON) \
to this:
$(abspath ../../components/esp-8266/cJSON) \

**Comment by PA7T** [comment]
thanks for the info. I will change that when I compile the code the next time and see, if this is also fine with my version.
